<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <None Remove="Icon.ico" />
        <None Remove="Icon.bmp" />
        <None Update="Raw\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
          </None>

    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Icon.ico">
            <LogicalName>Icon.ico</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Icon.bmp">
            <LogicalName>Icon.bmp</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DotTiled" Version="1.0.0" />
        <PackageReference Include="Gum.MonoGame" Version="2026.8.3.1" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.4.1" />
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.4.1" />
        <PackageReference Include="Nopipeline.Task" Version="2.3.0" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="../MonoTile/MonoTile.csproj" />
      <ProjectReference Include="../Opal/Opal.csproj" />
    </ItemGroup>
    <!-- Forces 'dotnet run' to build and invoke the native macOS entrypoint -->
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <OutputType>Exe</OutputType>
        <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
        <!-- Triggers native assembly wrapping on build -->
        <UseAppHost>true</UseAppHost>
    </PropertyGroup>

    <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <None Include="Info.plist" Link="Info.plist" CopyToOutputDirectory="Never" />
    </ItemGroup>
  </Project>
